### ISSUE TITLE
Did this work?

### ISSUE THREAD

**Issue by neverix** [shahbuland/openbci-2d-motion#2]
Hi,

Did this work in live mode? Or achieve a good validation accuracy

**Comment by shahbuland** [comment]
Results are highly anecdotal because I didn't do any legitimate form of eval. I *felt* like the mouse was moving according to my thoughts? Having done more signal processing stuff recently I'm a bit pessimistic that this may have been placebo since when I made this I was very new to ML and lacked any knowledge on techniques youd probably need to make use of time series data like EEG. Want to come back to this some day but currently don't know where the headset went after I moved 😅. I'm gonna add the above as a disclaimer to the repo itself, thanks for reminding me.

**Comment by neverix** [comment]
I see
